name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  zig-tests:
    runs-on: ubuntu-latest
    name: Zig Build Test (Multi-Version)
    strategy:
      matrix:
        zig-version: [master, 0.13.0, 0.12.1, 0.11.0]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ matrix.zig-version }}
      - name: Run Zig Tests
        run: |
          echo "Testing with Zig version: ${{ matrix.zig-version }}"
          zig version
          zig build test --summary all

  build-and-deploy-website:
    if: github.event_name == 'push'  # Only deploy on push, not PRs
    runs-on: ubuntu-latest
    name: Build and Deploy Docusaurus Site
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn
        working-directory: website

      - name: Build and Deploy
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
        working-directory: website
